### PR TITLE
Implementation of MOD-BME280 

### PR DESCRIPTION
**Pull request by fel115**
Issue #58

### CODE REVIEW

**Review by markus2330 — APPROVED** [review]
Does this work? Looks like a simple and good solution :+1:

**Comment by fel115** [comment]
@markus2330 it would work, but this module wouldn't do anything, because `s.board51 = None`. The handler which is called by the main function would always return `false`.

**Comment by fel115** [comment]
Everything should be functioning properly now. I've conducted testing on the code using a simulation of the `ttyACM0` device, as detailed in the `doc/DevelopmentSetup.md` documentation. Additionally, I've configured it to operate in sensor mode. An illustration of my configuration is presented below:
```toml
nextcloud.chat = "<chat-token>"
nextcloud.chat.licht = "<chat-token>"
nextcloud.chat.ping = "<chat-token>"
nextcloud.user = "<user>"
nextcloud.pass = "<password>"
nextcloud.url = "https://nextcloud.example.org/nextcloud"
environment.name = "Thermometer"
environment.device = "/dev/i2c-2"
environment.data.interval = 1
sensors."#0".loc = "Thermometer"
```
For the purpose of obtaining information every minute, I've set environment.data.interval = 1. Furthermore, I can confirm that the Nextcloud messages are also being successfully sent.

**Comment by markus2330** [comment]
Thx, looking forward to more. :rocket:

**Pull request merged**
