### PR TITLE
fix max wind bug in clima_sensor_us.rs

### PR DESCRIPTION
**Pull request by fel115**
#133

### CODE REVIEW

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
Thx for the fix! :heart:  There seem to be formatting issues. Will the error then be reported?

**Comment by fel115** [comment]
With the last commit `7f62023` the formatting should be fixed and error reporting is implemented.

**Comment by markus2330** [comment]
Great job, thank you! :heart:

**Pull request merged**
